version: '3.8'
services:
  ecp-ai:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: ecp-ai
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      - project-net

networks:
  project-net:
    external: true